Numpy:
- Stands for numerical python
- Allows us to work with multi-dimensional arrays (especially NumPy arrays, which are faster and more efficient than Python lists)
- Allows us to perform mathematical operations on arrays quickly and efficiently

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

#creating 1-d array
arr1 = np.array([1,2,3,4])  
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1


In [93]:
#converting 1-d array into 2-d array
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(5,1)) #5row 1col
print(arr2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5,)


In [97]:
#creating a 2-d array
arr2=np.array([[1,2,3],[4,5,6],[8,9,10]])
print(arr2)
print(arr2.shape) #get dimensions
print(arr2.ndim) #to get dimension
print(arr2.size) #get total number of elements
print(arr2.dtype) #get data type
print(arr2.itemsize) #to get itemsize in bytes

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
(3, 3)
2
9
int64
8


**Creating array Inbulit functions**

- np.arange(start,end,step) : is a similar function like range() which can take upto 3 parameters as an argument
- np.ones(row,col) : to create array of ones
- np.zeros(row,col) : to create array of zeros

In [85]:
#creating array with some inbuilt functions
print(np.arange(0,5).reshape(5,1))
print(np.ones((3,4)))
print(np.zeros((3,4)))
print(np.eye(3,3))


[[0]
 [1]
 [2]
 [3]
 [4]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [95]:
#numpy vectorized operations
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])

print(arr1+arr2) #element wise addition
print(arr1-arr2) #element wise substraction
print(arr1*arr2) #element wise multiplication
print(arr1*2) #multiply every element of arr1 with 2
print(arr1/arr2) #element wise division
print(arr1//arr2) #element wise floor division

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[2 4 6 8]
[1. 1. 1. 1.]
[1 1 1 1]


In [42]:
#universal function
arr=np.array([1,2,3])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]


In [4]:
#array slicing and Indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0]) #accesing 1st row
print(arr[1][2]) #accesing 2nd row 3rd col element
print(arr[1:]) #for getting all elements from 2nd row
print(arr[1:,2:]) #for getting all elements from 2nd row and 3rd column
print(arr[0:2,0:2])

[1 2 3]
6
[[4 5 6]
 [7 8 9]]
[[6]
 [9]]
[[1 2]
 [4 5]]


In [54]:
#modifying array elements
arr=np.array([[1,2],[3,4],[5,6]])
print(arr)
arr[0][0]=100
print(arr)
arr[1:]=200
print(arr)

[[1 2]
 [3 4]
 [5 6]]
[[100   2]
 [  3   4]
 [  5   6]]
[[100   2]
 [200 200]
 [200 200]]


In [55]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [71]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
print("Median:", np.median(data))

# Standard deviation
print("Standard Deviation:",np.std(data))

# Variance
print("Variance:", np.var(data))

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [81]:
# logical operations
data=np.array([2,3,4,5,6,7,8])
print(data>5)
print(data[data>3])
print(data[(data>4) & (data<7)])


[False False False False  True  True  True]
[4 5 6 7 8]
[5 6]
