### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np
array = np.random.randint(1, 21, size=(5, 5))
print(array,"\n")

array[0:,2:3]=1
print(array)

[[19 15 16 13 10]
 [10 15 16 16  6]
 [ 8 18  3  3 14]
 [10  3 17  7  3]
 [ 7 14  4  3  4]] 

[[19 15  1 13 10]
 [10 15  1 16  6]
 [ 8 18  1  3 14]
 [10  3  1  7  3]
 [ 7 14  1  3  4]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr,"\n")
np.fill_diagonal(arr,0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
arr=np.arange(1,37).reshape(6,6)
print(arr,"\n")
sub_arr=arr[2:5,1:4]
print(sub_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]] 

[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr=np.random.randint(10,51,size=(5,5))
print(arr,"\n")

sub_arr=np.concatenate((arr[0], arr[1:-1,-1], arr[-1][::-1], arr[1:-1,0][::-1] ))
print(sub_arr)

[[27 14 33 48 21]
 [44 29 19 31 37]
 [22 33 15 38 49]
 [36 40 20 46 42]
 [19 13 21 45 19]] 

[27 14 33 48 21 37 49 42 19 45 21 13 19 36 22 44]


### Assignment 3: Array Operations

1. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr,"\n")

row_wise=np.sum(arr,axis=1)
print(row_wise)
column_wise=np.sum(arr,axis=0)
print(column_wise)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[10 26 42 58]
[28 32 36 40]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
arr=np.random.randint(1,11,size=(3,3))
print(arr,"\n")
row_array=np.random.randint(1,11,size=(3,))
print(row_array,"\n")
result=arr+row_array
print(result)

[[ 1  8  2]
 [ 2  5  3]
 [10  3  6]] 

[1 5 3] 

[[ 2 13  5]
 [ 3 10  6]
 [11  8  9]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
arr=np.random.randint(1,11,size=(4,4))
column_array=np.random.randint(1,11,size=(4,1))
result=arr-column_array
print(arr,"\n")
print(column_array,"\n")
print(result)

[[5 4 7 3]
 [1 4 6 5]
 [9 9 9 6]
 [7 5 6 4]] 

[[4]
 [9]
 [9]
 [3]] 

[[ 1  0  3 -1]
 [-8 -5 -3 -4]
 [ 0  0  0 -3]
 [ 4  2  3  1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
array=np.random.randint(1,11,size=(3,3))
print(array,"\n")

determinant=np.linalg.det(array)
inverse=np.linalg.inv(array)
eigen_value=np.linalg.eigvals(array)
print(determinant)
print(inverse)
print(eigen_value)

[[10  3 10]
 [ 9  2  3]
 [ 7  5 10]] 

152.99999999999997
[[ 0.03267974  0.13071895 -0.07189542]
 [-0.45098039  0.19607843  0.39215686]
 [ 0.20261438 -0.18954248 -0.04575163]]
[21.01403261+0.j          0.4929837 +2.65288827j  0.4929837 -2.65288827j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
result = np.dot(array1, array2)

print(array1,"\n")
print(array2,"\n")
print(result)

[[ 4 10  5]
 [ 5  7  1]] 

[[6 8]
 [7 9]
 [3 1]] 

[[109 127]
 [ 82 104]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:
array=np.arange(1,10).reshape(3,3)
print(array,"\n")

array1=array.reshape(1,9)
print(array1,"\n")

array2=array1.reshape(9,1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3 4 5 6 7 8 9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [5]:
array = np.random.randint(1, 21, size=(5, 5))
print(array,"\n")

flatten_array=array.flatten() #converts the 2D array to a 1D array.
print(flatten_array,"\n")

print(flatten_array.reshape(5,5))

[[ 2 10  4 18  6]
 [ 7  1  8  4  6]
 [12 12  2  1 17]
 [11 10 17 19  7]
 [19 13 19  3  5]] 

[ 2 10  4 18  6  7  1  8  4  6 12 12  2  1 17 11 10 17 19  7 19 13 19  3
  5] 

[[ 2 10  4 18  6]
 [ 7  1  8  4  6]
 [12 12  2  1 17]
 [11 10 17 19  7]
 [19 13 19  3  5]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [15]:
array=np.random.randint(1,11,size=(5,5))
print(array,"\n")

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]] #array[[rows],[columns]]
print(corners,"\n")

[[ 2 10  6  9  1]
 [ 2  5  7  6  8]
 [ 6  9  7  9  9]
 [ 6  8  7 10  4]
 [ 4 10  3  4  3]] 

[2 1 4 3] 



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:
array = np.random.randint(1, 21, size=(4, 4))
print(array,"\n")
array[array > 10]=10
print(array)


[[17 10 14  3]
 [10 10  8  3]
 [12  5  1 12]
 [ 7 14 14 17]] 

[[10 10 10  3]
 [10 10  8  3]
 [10  5  1 10]
 [ 7 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[18  1 13 17]
 [12  5 20  6]
 [ 6 18 12 18]
 [10 15 17 10]]
Masked array:
[[-- 1 -- --]
 [-- 5 -- 6]
 [6 -- -- --]
 [10 -- -- 10]]
Sum of unmasked elements: 38


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [87]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[11  3  8]
 [20  2 16]
 [10 18  8]]
Masked array:
[[-- 3 8]
 [20 -- 16]
 [10 18 --]]
Modified masked array:
[[12  3  8]
 [20 12 16]
 [10 18 12]]
